---
language: node_js
node_js:
  - "4"

sudo: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  - CXX=g++-4.8

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - sudo rm -rf /usr/local/phantomjs/bin/phantomjs
  - sudo mv phantomjs /usr/local/phantomjs/bin/phantomjs
  - npm config set spin false
  - npm install -g npm@^2

install:
  - npm install -g bower
  - npm install
  - bower install --force-latest

script:
  - npm test
